name: Deploy API

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  ci:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 6
      - uses: pnpm/action-setup@v2.4.0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm api:build
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          NITRO_PRESET: cloudflare

      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          vars: WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
