name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Label PRs
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto-assign to core PRs
        if: contains(github.event.pull_request.labels.*.name, 'core')
        uses: kentaro-m/auto-assign-action@v1
        with:
          assignees: [taskylizard]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
